version: '3.7'

volumes:
    app_volume:
        name: ${PROJECT_NAME}_app_volume
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${PWD}"

services:
    php:
        container_name: ${PROJECT_NAME}_php
        build:
            context: ./..
            dockerfile: ./docker/php-fpm/Dockerfile
            args:
                PROJECT_NAME: ${PROJECT_NAME}
                APP_ENV: ${APP_ENV}
                TIMEZONE: ${TIMEZONE}
        ports:
            - 9000:9000
        volumes:
            - app_volume:/app
        depends_on:
            db:
                condition: service_healthy

    db:
        container_name: ${PROJECT_NAME}_db
        image: mysql:8.0
        command: ["--default-authentication-plugin=mysql_native_password"]
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 20s
            retries: 10
        ports:
            - 3306:3306
        user: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    nginx:
        container_name: ${PROJECT_NAME}_nginx
        image: nginx:1.19-alpine
        depends_on:
            - php
        ports:
            - 80:80
        volumes:
            - ./nginx/templates:/etc/nginx/templates
            - app_volume:/app:ro
        environment:
            PROJECT_NAME: ${PROJECT_NAME}
            DOMAIN: ${DOMAIN}
