---
-
    name: '{{ deploy_from_branch }} | Check .env in share'
    copy:
        src: '{{ ansistrano_release_path.stdout }}/.env'
        dest: '{{ ansistrano_release_path.stdout }}/../../shared/.env.local'
        remote_src: yes
        force: no
