monolog:
    handlers:
        main:
            type: fingers_crossed
            excluded_http_codes: [ 404 ]
            handler: nested
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
