parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $yandexApiKey: '%env(YANDEX_MAP_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    Linkin\Component\DoctrineNamingStrategy\ORM\Mapping\CamelCaseNamingStrategy: ~

    guzzle.client:
        class: GuzzleHttp\Client

    GuzzleHttp\ClientInterface: '@guzzle.client'
